---

apiVersion: v1
kind: Namespace
metadata:
  name: evil

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: evilpetclinic
  name: evilpetclinic
  namespace: evil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evilpetclinic
  template:
    metadata:
      labels:
        app: evilpetclinic
    spec:
      containers:
      - image: itresoldi/evilpetclinic:latest
        name: evilpetclinic
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          name: evilpetclinic
          protocol: TCP
      imagePullSecrets:
      - name: regcred
      securityContext:
        runAsUser: 0
      hostNetwork: false

---

apiVersion: v1
kind: Service
metadata:
  name: evilpetclinic-svc
  namespace: evil
spec:
  type: NodePort
  selector:
    app: evilpetclinic
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
